CREATE TABLE sensor(
    name VARCHAR(200) UNIQUE PRIMARY KEY
)

CREATE TABLE measure(
    measure_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperature INTEGER CHECK (temperature > -237 AND temperature < 237) NOT NULL,
    raining BOOLEAN NOT NULL,
    sensor_name VARCHAR(200) REFERENCES sensor(name) ON DELETE CASCADE
)